
   
### GET all users

GET http://localhost:3000/api/users/ HTTP/1.1

### GET a single user

GET http://localhost:3000/api/users/Tri HTTP/1.1

### GET a single user which doesn't exist

GET http://localhost:3000/api/users/Tra HTTP/1.1

### Delete a user, which exists
DELETE http://localhost:3000/api/users/Tri HTTP/1.1

### Delete a user, which DOES NOT exist
DELETE http://localhost:3000/api/users/DingDong

### POST a user
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "TriTra-Bob",
    "email": "bobby@bobbymail.com",
    "password": "GrinchiFlinchi"

}

### LOGIN JOSEF
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "name": "Josef",
    "password": "3456"

}

### LOGIN MARIA
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "name": "Maria",
    "password": "2345"

}





### LOGGED IN USER
GET http://localhost:3000/api/me HTTP/1.1

